branches:
    # whitelist
    only:
        - master
        - develop
language: python
python:
   - "3.3"
# command to install the dependancies
install:
    - "sudo apt-add-repository -y \"deb http://ubuntu.mirror.cambrium.nl/ubuntu/ quantal main\""
    - "sudo apt-get update"
    - "sudo apt-get install gcc g++ build-essential python3-dev"
before_script: 
   - "git submodule update --init"
   - "gcc --version"
   - "cd lib/libsaturn && cmake . -DCMAKE_CXX_FLAGS=-fPIC && make libsaturn && cd ../.."
notifications:
  irc: "irc.freenode.net#0x10c-galaxy"

script: "python3 setup.py install"
after_script: "python3 run_tests.py"
